import { COLORS } from "./colors.js";

export const drawFooter = (doc, startY) => {

  const pageWidth = doc.page.width;

  // Divider
  doc
    .moveTo(40, startY+10)
    .lineTo(pageWidth - 40, startY+10)
    .lineWidth(1)
    .stroke(COLORS.border);

  const footerY = startY + 15;

  doc
    .fillColor(COLORS.gray)
    .font("Helvetica")
    .fontSize(9)
    .text("Generated by HaqDar", 40, footerY);

  doc
    .text(
      "Government Scheme Recommendation Platform",
      0,
      footerY,
      {
        width: pageWidth,
        align: "center",
      }
    );

  doc
    .text(
      new Date().toLocaleString("en-IN"),
      pageWidth - 180,
      footerY,
      {
        width: 140,
        align: "right",
      }
    );
};